// Mock data for admin dashboard testing
export const mockStats = {
  properties: {
    total: 1250,
    active: 890,
    pending: 145,
    inactive: 215,
    featured: 67,
    rejected: 3,
  },
  users: {
    totalTenants: 5420,
    totalOwners: 1850,
    newThisMonth: 342,
    verified: 6840,
    blocked: 45,
  },
  inquiries: {
    total: 2340,
    today: 45,
    thisWeek: 287,
    newLeads: 124,
    closedDeals: 156,
  },
  bookings: {
    confirmed: 234,
    ongoing: 87,
    completed: 445,
    cancelled: 23,
  },
  revenue: {
    totalRevenue: 245000,
    pendingPayments: 45000,
    monthlyRecurring: 89000,
  },
  topCities: [
    { city: 'Lucknow', count: 342 },
    { city: 'Prayagraj', count: 298 },
    { city: 'Kanpur', count: 267 },
    { city: 'Varanasi', count: 198 },
    { city: 'Agra', count: 145 },
  ],
  conversionRate: 6.67,
  growthMetrics: {
    propertiesGrowth: 12,
    usersGrowth: 8,
    inquiriesGrowth: 15,
  },
  recentActivity: [
    {
      _id: '1',
      action: 'property_posted',
      actorId: 'owner1',
      targetId: 'prop1',
      targetType: 'property',
      metadata: {},
      timestamp: new Date(),
      description: 'New property: 2BHK Flat in Lucknow',
    },
    {
      _id: '2',
      action: 'property_posted',
      actorId: 'owner2',
      targetId: 'prop2',
      targetType: 'property',
      metadata: {},
      timestamp: new Date(),
      description: 'New property: PG in Prayagraj',
    },
  ],
};

export const mockProperties = [
  {
    _id: 'prop1',
    title: '2BHK Luxury Flat',
    location: { address: 'Gomti Nagar', city: 'Lucknow', state: 'UP' },
    propertyType: 'apartment',
    bedrooms: 2,
    bathrooms: 1,
    price: 15000,
    ownerId: 'owner1',
    ownerName: 'Rajesh Kumar',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=500'],
    isVerified: false,
    viewCount: 245,
    averageRating: 4.5,
    totalReviews: 12,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    _id: 'prop2',
    title: 'Single Room PG',
    location: { address: 'Vishwanath Ganj', city: 'Prayagraj', state: 'UP' },
    propertyType: 'condo',
    bedrooms: 1,
    bathrooms: 1,
    price: 5000,
    ownerId: 'owner2',
    ownerName: 'Priya Singh',
    status: 'active',
    images: ['https://images.unsplash.com/photo-1554995207-c18210bbed38?w=500'],
    isVerified: true,
    viewCount: 567,
    averageRating: 4.8,
    totalReviews: 28,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

export const mockInquiries = [
  {
    _id: 'inq1',
    tenantId: 'tenant1',
    tenantName: 'Akshay Sharma',
    tenantPhone: '9876543210',
    propertyId: 'prop1',
    propertyTitle: '2BHK Luxury Flat',
    ownerId: 'owner1',
    ownerName: 'Rajesh Kumar',
    inquiryDate: new Date(),
    inquiryTime: '14:30',
    status: 'new_lead',
    statusHistory: [],
    source: 'app',
    followUpDate: undefined,
    priority: 'high',
    tags: ['urgent'],
  },
  {
    _id: 'inq2',
    tenantId: 'tenant2',
    tenantName: 'Priya Verma',
    tenantPhone: '9123456789',
    propertyId: 'prop2',
    propertyTitle: 'Single Room PG',
    ownerId: 'owner2',
    ownerName: 'Priya Singh',
    inquiryDate: new Date(),
    inquiryTime: '10:15',
    status: 'call_done',
    statusHistory: [],
    source: 'website',
    followUpDate: new Date(),
    priority: 'medium',
    tags: [],
  },
];

export const mockUsers = [
  {
    _id: 'admin1',
    username: 'admin',
    email: 'admin@ssthomesolutions.com',
    phone: '9999999999',
    registrationDate: new Date(),
    fraudRiskLevel: 'none',
    isActive: true,
    lastActivity: new Date(),
    trustBadges: ['admin'],
    role: 'admin',
  },
  {
    _id: 'owner1',
    username: 'rajesh_kumar',
    email: 'rajesh@example.com',
    phone: '9876543210',
    city: 'Lucknow',
    isVerified: false,
    propertyCount: 5,
    totalListings: 5,
    activeListings: 3,
    responseRate: 95,
    avgResponseTimeHours: 2,
    fraudRiskLevel: 'low',
    trustBadges: ['responsive'],
    registrationDate: new Date(),
    lastActivity: new Date(),
    walletBalance: 5000,
    planType: 'pro',
    planExpiresAt: new Date(),
    isActive: true,
    role: 'owner',
  },
  {
    _id: 'tenant1',
    username: 'akshay_sharma',
    email: 'akshay@example.com',
    phone: '9123456789',
    registrationDate: new Date(),
    inquiriesCount: 3,
    activeInquiries: 1,
    bookingsCount: 1,
    fraudRiskLevel: 'low',
    tenantVerified: true,
    responseRate: 100,
    isActive: true,
    lastActivity: new Date(),
    trustBadges: ['verified'],
    role: 'tenant',
  },
];
